Use explicit return for f==-1
to fix compilation in clang

[   15s] clang-tidy src/devrand.cpp -- -g -O3 -std=c++14 -Wall -I include -I cxxopts/include -I /usr/include/libseccomp -D_GNU_SOURCE=1 -D_POSIX_C_SOURCE=20181101 -D__USE_XOPEN=1 -DAPP_VERSI
ON=\"0.2.3\" -DAPP_BUILDID=\"0\" -O0 -Wall -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type
[   15s] 2 warnings generated.
[   15s] /home/abuild/rpmbuild/BUILD/dettrace-git1731583983.74dced2/src/devrand.cpp:91:7: error: The 1st argument to 'fsync' is -1 but should be >= 0 [clang-analyzer-unix.StdCLibraryFunction
s,-warnings-as-errors]
[   15s]    91 |       fsync(fd);
[   15s]       |       ^     ~~
[   15s] /home/abuild/rpmbuild/BUILD/dettrace-git1731583983.74dced2/src/devrand.cpp:71:12: note: Assuming that 'open' fails
[   15s]    71 |   int fd = open(t->fifo.c_str(), O_RDWR);
[   15s]       |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   15s] /home/abuild/rpmbuild/BUILD/dettrace-git1731583983.74dced2/src/devrand.cpp:71:3: note: 'fd' initialized here
[   15s]    71 |   int fd = open(t->fifo.c_str(), O_RDWR);
[   15s]       |   ^~~~~~